queue_rules:
  - name: default
    conditions:
      - "status-success=continuous-integration/appveyor/branch"
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=security/snyk (lukemnet)"

pull_request_rules:
  - name: Automatic merge of Snyk dependency upgrades (bot)
    conditions:
      - "author=snyk-bot"
      - "-conflict"
      - "status-success=continuous-integration/appveyor/branch"
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=security/snyk (lukemnet)"
    actions:
      queue:
        method: squash
        name: default
  - name: Automatic merge of Snyk dependency upgrades (me)
    conditions:
      - "author=lwojcik"
      - "title~=[Snyk]"
      - "title~=Upgrade"
      - "-conflict"
      - "status-success=continuous-integration/appveyor/branch"
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=security/snyk (lukemnet)"
    actions:
      queue:
        method: squash
        name: default
  - name: Automatic merge of Dependabot dependency upgrades
    conditions:
      - "author=dependabot[bot]"
      - "-conflict"
      - "status-success=continuous-integration/appveyor/branch"
      - "status-success=continuous-integration/appveyor/pr"
      - "status-success=security/snyk (lukemnet)"
    actions:
      queue:
        method: squash
        name: default